on: [push]

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Lint code
        run: swiftformat --lint .
